server:
  port: 7003
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true #是否向eureka注册中心注册自己
    fetch-registry: false #表示自己就是注册中心
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

