server:
  port: 7001
spring:
  application:
    name: springcould-provider-7001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://119.29.79.237:3306/school?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver